### ISSUE TITLE
Build error with presto-0.180

### ISSUE THREAD

**Issue by KhoaTheBest** [airbnb/airpal#222]
I used this command "./gradlew -Dairpal.prestoVersion=0.180 clean shadowJar" to build with presto version 0.180. But bundle of errors:
```
:cleanAssets UP-TO-DATE
:clean
:nodeSetup UP-TO-DATE
:installAssets
:buildAssets
[09:35:59] Using gulpfile ~/airpal/src/main/resources/assets/gulpfile.js
[09:35:59] Starting 'browserify'...
[09:35:59] Bundling app.js...
[09:35:59] Bundling plugin.js...
[09:36:14] Bundled plugin.js in 15 s
[09:36:22] Bundled app.js in 23 s
[09:36:22] Finished 'browserify' after 23 s
:compileJava
/home/khoale/airpal/src/main/java/com/airbnb/airpal/presto/QueryRunner.java:30: error: constructor StatementClient in class StatementClient cannot be applied to given types;
        return new StatementClient(httpClient, queryResultsCodec, session, query);
               ^
  required: OkHttpClient,ClientSession,String
  found: HttpClient,JsonCodec<QueryResults>,ClientSession,String
  reason: actual and formal argument lists differ in length
/home/khoale/airpal/src/main/java/com/airbnb/airpal/presto/ClientSessionFactory.java:45: error: no suitable constructor found for ClientSession(URI,String,String,String,String,String,Locale,ImmutableMap<String,String>,<null>,boolean,Duration)
        return new ClientSession(server.get(),
               ^
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
/home/khoale/airpal/src/main/java/com/airbnb/airpal/presto/ClientSessionFactory.java:61: error: no suitable constructor found for ClientSession(URI,String,String,String,String,String,Locale,ImmutableMap<String,String>,<null>,boolean,Duration)
        return new ClientSession(server.get(),
               ^
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
/home/khoale/airpal/src/main/java/com/airbnb/airpal/presto/ClientSessionFactory.java:77: error: no suitable constructor found for ClientSession(URI,String,String,String,String,String,Locale,ImmutableMap<String,String>,<null>,boolean,Duration)
        return new ClientSession(server.get(),
               ^
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
    constructor ClientSession.ClientSession(URI,String,String,String,String,String,String,Locale,Map<String,String>,Map<String,String>,String,boolean,Duration) is not applicable
      (actual and formal argument lists differ in length)
/home/khoale/airpal/src/main/java/com/airbnb/airpal/presto/Table.java:80: error: incompatible types: ConnectorId cannot be converted to String
        return new Table(input.getConnectorId(), input.getSchema(), input.getTable(), columns);
                                             ^
/home/khoale/airpal/src/main/java/com/airbnb/airpal/core/execution/Execution.java:305: error: no suitable constructor found for QueryStats(DateTime,<null>,DateTime,DateTime,Duration,Duration,Duration,Duration,Duration,Duration,int,int,int,int,int,int,int,double,DataSize,DataSize,Duration,Duration,Duration,Duration,boolean,ImmutableSet<Object>,DataSize,int,DataSize,int,DataSize,int)
        return new QueryStats(
               ^
    constructor QueryStats.QueryStats() is not applicable
      (actual and formal argument lists differ in length)
    constructor QueryStats.QueryStats(DateTime,DateTime,DateTime,DateTime,Duration,Duration,Duration,Duration,Duration,Duration,int,int,int,int,int,int,int,int,double,DataSize,DataSize,boolean,Duration,Duration,Duration,Duration,boolean,Set<BlockedReason>,DataSize,long,DataSize,long,DataSize,long,List<OperatorStats>) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/khoale/airpal/src/main/java/com/airbnb/airpal/AirpalApplicationBase.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
6 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Any suggestion?

Thanks in advance
Khoa

**Comment by desavera** [comment]
Same problem with Presto 0.177 ... it does not compile ... hard to admit !

**Comment by xiaoshuai** [comment]
is still being maintained？

**Comment by M2shad0w** [comment]
@Xiaoshuai  not

**Comment by mirandazhjm** [comment]
Same here with Presto 0.187

**Comment by leemengtw** [comment]
Similar issus with Presto 0.189 ..

```
  symbol:   variable this
  location: class AirpalUserFactory
/home/ec2-user/airpal/src/main/java/com/airbnb/airpal/core/AirpalUserFactory.java:21: error: cannot find symbol
        this.defaultAccessLevel = accessLevel;
        ^
  symbol:   variable this
  location: class AirpalUserFactory
/home/ec2-user/airpal/src/main/java/com/airbnb/airpal/core/AirpalUserFactory.java:24: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ec2-user/airpal/src/main/java/com/airbnb/airpal/AirpalApplicationBase.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
12 errors
:compileJava FAILED
```

Since the repository is not maintained now, hard to fix this problem..
